site_name: EMTOP TECHNOLOGY CO.,LTD.
site_url: https://wiki.emtop-tech.com
theme:
  name: readthedocs
copyright: |
  &copy; 2023 <a href="https://www.emtop-tech.com"  target="_blank" rel="noopener">EMTOP</a>

nav:
- Home: index.md
- NXP Series:  ###一级标题
  - NXP i.MX8M Plus: nxp-series/nxp-imx8m-plus.md ### 二级标题：目录／文件名
  - NXP i.MX8M MINI: nxp-series/nxp-imx8m-mini.md
  - NXP i.MX6ull: nxp-series/nxp.imx6ull.md
- TI Series: 
  - TI AM62X:  ti-series/ti-am62x.md
  - TI AM5728: ti-series/ti-am5728.md
  - TI AM4378: ti-series/ti-am4378.md
  - TI AM3358: ti-series/ti-am3358.md
- ADD ON Board: 
  - LCD8000-70C: add-on-board/lcd8000-70c.md
  - MIPI-70C: add-on-board/mipi-7c.md
- Amazon Series:
  - U2RS232X4: amazon-series/u2rs232x4.md

markdown_extentions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search

extra_css:
  - resources/css/extra.css